"""create_meeting_recaps_table

Revision ID: 0a10fb35f446
Revises: 02ddbe2acae5
Create Date: 2026-01-22 12:43:44.963943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a10fb35f446'
down_revision: Union[str, Sequence[str], None] = '02ddbe2acae5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_recaps',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('project_id', sa.CHAR(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('meeting_date', sa.Date(), nullable=False),
    sa.Column('raw_input', sa.Text(), nullable=False),
    sa.Column('input_type', sa.Enum('txt', 'md', name='inputtype'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'processed', 'failed', 'applied', name='meetingstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('failed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('prompt_version', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meeting_recaps')
    # ### end Alembic commands ###
