"""create_requirements_table

Revision ID: 2f79be4b75bf
Revises: 96e4c628927a
Create Date: 2026-01-22 18:35:19.745894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f79be4b75bf'
down_revision: Union[str, Sequence[str], None] = '96e4c628927a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requirements',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('project_id', sa.CHAR(length=36), nullable=False),
    sa.Column('section', sa.Enum('problems', 'user_goals', 'functional_requirements', 'data_needs', 'constraints', 'non_goals', 'risks_assumptions', 'open_questions', 'action_items', name='section'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_requirements_project_active', 'requirements', ['project_id', 'is_active'], unique=False)
    op.create_index('ix_requirements_project_section', 'requirements', ['project_id', 'section'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_requirements_project_section', table_name='requirements')
    op.drop_index('ix_requirements_project_active', table_name='requirements')
    op.drop_table('requirements')
    # ### end Alembic commands ###
