"""create requirement_sources table

Revision ID: 4a7f1d3ecf25
Revises: 2f79be4b75bf
Create Date: 2026-01-22 18:38:22.277566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a7f1d3ecf25'
down_revision: Union[str, Sequence[str], None] = '2f79be4b75bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requirement_sources',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('requirement_id', sa.CHAR(length=36), nullable=False),
    sa.Column('meeting_id', sa.CHAR(length=36), nullable=True),
    sa.Column('meeting_item_id', sa.CHAR(length=36), nullable=True),
    sa.Column('source_quote', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting_recaps.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['meeting_item_id'], ['meeting_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_requirement_sources_meeting_id', 'requirement_sources', ['meeting_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_requirement_sources_meeting_id', table_name='requirement_sources')
    op.drop_table('requirement_sources')
    # ### end Alembic commands ###
