"""create_requirement_history_table

Revision ID: 77d97144f4ea
Revises: 4a7f1d3ecf25
Create Date: 2026-01-22 18:41:49.159712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77d97144f4ea'
down_revision: Union[str, Sequence[str], None] = '4a7f1d3ecf25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requirement_history',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('requirement_id', sa.CHAR(length=36), nullable=False),
    sa.Column('meeting_id', sa.CHAR(length=36), nullable=True),
    sa.Column('actor', sa.Enum('system', 'user', 'ai_extraction', 'ai_merge', name='actor'), nullable=False),
    sa.Column('action', sa.Enum('created', 'modified', 'deactivated', 'reactivated', 'merged', name='action'), nullable=False),
    sa.Column('old_content', sa.Text(), nullable=True),
    sa.Column('new_content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting_recaps.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_requirement_history_requirement_id', 'requirement_history', ['requirement_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_requirement_history_requirement_id', table_name='requirement_history')
    op.drop_table('requirement_history')
    # ### end Alembic commands ###
