"""create meeting_items table

Revision ID: 96e4c628927a
Revises: 0a10fb35f446
Create Date: 2026-01-22 12:49:09.936393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96e4c628927a'
down_revision: Union[str, Sequence[str], None] = '0a10fb35f446'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_items',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('meeting_id', sa.CHAR(length=36), nullable=False),
    sa.Column('section', sa.Enum('problems', 'user_goals', 'functional_requirements', 'data_needs', 'constraints', 'non_goals', 'risks_assumptions', 'open_questions', 'action_items', name='section'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_quote', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting_recaps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_meeting_items_meeting_section', 'meeting_items', ['meeting_id', 'section'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_meeting_items_meeting_section', table_name='meeting_items')
    op.drop_table('meeting_items')
    # ### end Alembic commands ###
