"""create meeting_item_decisions table

Revision ID: d14d0c3d54db
Revises: 77d97144f4ea
Create Date: 2026-01-22 19:42:20.648960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd14d0c3d54db'
down_revision: Union[str, Sequence[str], None] = '77d97144f4ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_item_decisions',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('meeting_item_id', sa.CHAR(length=36), nullable=False),
    sa.Column('decision', sa.Enum('added', 'skipped_duplicate', 'skipped_semantic', 'conflict_keep_existing', 'conflict_replaced', 'conflict_kept_both', 'conflict_merged', name='decision'), nullable=False),
    sa.Column('matched_requirement_id', sa.CHAR(length=36), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['matched_requirement_id'], ['requirements.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['meeting_item_id'], ['meeting_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_meeting_item_decisions_meeting_item_id', 'meeting_item_decisions', ['meeting_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_meeting_item_decisions_meeting_item_id', table_name='meeting_item_decisions')
    op.drop_table('meeting_item_decisions')
    # ### end Alembic commands ###
