"""create_jira_story_table

Revision ID: j7k8l9m0n1o2
Revises: i6j7k8l9m0n1
Create Date: 2026-01-29 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'j7k8l9m0n1o2'
down_revision: Union[str, Sequence[str], None] = 'i6j7k8l9m0n1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jira_story',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('project_id', sa.CHAR(length=36), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('problem_statement', sa.Text(), nullable=True),
    sa.Column('target_user_roles', sa.Text(), nullable=True),
    sa.Column('data_sources', sa.Text(), nullable=True),
    sa.Column('business_rules', sa.Text(), nullable=True),
    sa.Column('response_example', sa.Text(), nullable=True),
    sa.Column('acceptance_criteria', sa.Text(), nullable=True),
    sa.Column('reporter', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('parent_jira_id', sa.Integer(), nullable=True),
    sa.Column('date_cr', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jira_story_date_cr', 'jira_story', ['date_cr'], unique=False)
    op.create_index('ix_jira_story_parent_jira_id', 'jira_story', ['parent_jira_id'], unique=False)
    op.create_index('ix_jira_story_project_id', 'jira_story', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_jira_story_project_id', table_name='jira_story')
    op.drop_index('ix_jira_story_parent_jira_id', table_name='jira_story')
    op.drop_index('ix_jira_story_date_cr', table_name='jira_story')
    op.drop_table('jira_story')
    # ### end Alembic commands ###
