"""Pydantic schemas for API request/response validation."""

from app.schemas.jira_story import (
    JiraStoryCreate,
    JiraStoryResponse,
    JiraStoriesSaveRequest,
    JiraStoriesSaveResponse,
)
from app.schemas.auth import (
    TokenResponse,
    UserLogin,
    UserRegister,
    UserResponse,
)
from app.schemas.meeting import (
    ApplyResponse,
    ConflictResultResponse,
    MatchedRequirementResponse,
    MeetingItemCreate,
    MeetingItemReorderRequest,
    MeetingItemResponse,
    MeetingItemUpdate,
    MeetingListItemResponse,
    MeetingResponse,
    MeetingUpload,
    MergeSuggestionRequest,
    MergeSuggestionResponse,
    ResolveDecision,
    ResolveRequest,
    ResolveResponse,
    UploadResponse,
)
from app.schemas.project import (
    ExportStatusSchema,
    MockupsStatusSchema,
    PRDStageStatusSchema,
    ProgressResponse,
    ProjectCreate,
    ProjectList,
    ProjectResponse,
    ProjectStatsResponse,
    ProjectUpdate,
    RequirementsStatusSchema,
    SectionCount,
    StageStatusEnum,
    StageUpdateRequest,
    StoriesStatusSchema,
    calculate_progress,
)
from app.schemas.requirement import (
    RequirementCreate,
    RequirementHistoryResponse,
    RequirementReorderRequest,
    RequirementResponse,
    RequirementsListResponse,
    RequirementSourceResponse,
    RequirementUpdate,
)
__all__ = [
    # Auth schemas
    "UserRegister",
    "UserLogin",
    "TokenResponse",
    "UserResponse",
    # Project schemas
    "ProjectCreate",
    "ProjectUpdate",
    "ProjectResponse",
    "ProjectList",
    "SectionCount",
    "ProjectStatsResponse",
    "ProgressResponse",
    "StageStatusEnum",
    "StageUpdateRequest",
    "RequirementsStatusSchema",
    "PRDStageStatusSchema",
    "StoriesStatusSchema",
    "MockupsStatusSchema",
    "ExportStatusSchema",
    "calculate_progress",
    # Meeting schemas
    "MeetingUpload",
    "MeetingItemResponse",
    "MeetingResponse",
    "MeetingListItemResponse",
    "UploadResponse",
    "MeetingItemUpdate",
    "MeetingItemCreate",
    "MeetingItemReorderRequest",
    "MatchedRequirementResponse",
    "ConflictResultResponse",
    "ApplyResponse",
    "MergeSuggestionRequest",
    "MergeSuggestionResponse",
    "ResolveDecision",
    "ResolveRequest",
    "ResolveResponse",
    # Requirement schemas
    "RequirementCreate",
    "RequirementSourceResponse",
    "RequirementHistoryResponse",
    "RequirementResponse",
    "RequirementUpdate",
    "RequirementsListResponse",
    "RequirementReorderRequest",
    # JIRA Story schemas
    "JiraStoryCreate",
    "JiraStoryResponse",
    "JiraStoriesSaveRequest",
    "JiraStoriesSaveResponse",
]
