"""Pydantic schemas for API request/response validation."""

from app.schemas.meeting import (
    ApplyResponse,
    ConflictResultResponse,
    MatchedRequirementResponse,
    MeetingItemCreate,
    MeetingItemReorderRequest,
    MeetingItemResponse,
    MeetingItemUpdate,
    MeetingListItemResponse,
    MeetingResponse,
    MeetingUpload,
    MergeSuggestionRequest,
    MergeSuggestionResponse,
    ResolveDecision,
    ResolveRequest,
    ResolveResponse,
    UploadResponse,
)
from app.schemas.prd import (
    ExportFormat,
    PaginatedResponse,
    PRDExportJSON,
    PRDExportSection,
    PRDGenerateRequest,
    PRDResponse,
    PRDSection,
    PRDStatusResponse,
    PRDSummary,
    PRDUpdateRequest,
)
from app.schemas.project import (
    ExportStatusSchema,
    MockupsStatusSchema,
    PRDStageStatusSchema,
    ProgressResponse,
    ProjectCreate,
    ProjectList,
    ProjectResponse,
    ProjectStatsResponse,
    ProjectUpdate,
    RequirementsStatusSchema,
    SectionCount,
    StageStatusEnum,
    StageUpdateRequest,
    StoriesStatusSchema,
    calculate_progress,
)
from app.schemas.requirement import (
    RequirementCreate,
    RequirementHistoryResponse,
    RequirementReorderRequest,
    RequirementResponse,
    RequirementsListResponse,
    RequirementSourceResponse,
    RequirementUpdate,
)
from app.schemas.user_story import (
    ReorderRequest,
    STORIES_CSV_COLUMNS,
    StoriesExportJSON,
    StoriesGenerateRequest,
    StoryBatchResponse,
    StoryBatchStatusResponse,
    StoryCreateRequest,
    StoryExportFormat,
    StoryExportItem,
    StoryUpdateRequest,
    UserStoryResponse,
)

__all__ = [
    # Project schemas
    "ProjectCreate",
    "ProjectUpdate",
    "ProjectResponse",
    "ProjectList",
    "SectionCount",
    "ProjectStatsResponse",
    "ProgressResponse",
    "StageStatusEnum",
    "StageUpdateRequest",
    "RequirementsStatusSchema",
    "PRDStageStatusSchema",
    "StoriesStatusSchema",
    "MockupsStatusSchema",
    "ExportStatusSchema",
    "calculate_progress",
    # Meeting schemas
    "MeetingUpload",
    "MeetingItemResponse",
    "MeetingResponse",
    "MeetingListItemResponse",
    "UploadResponse",
    "MeetingItemUpdate",
    "MeetingItemCreate",
    "MeetingItemReorderRequest",
    "MatchedRequirementResponse",
    "ConflictResultResponse",
    "ApplyResponse",
    "MergeSuggestionRequest",
    "MergeSuggestionResponse",
    "ResolveDecision",
    "ResolveRequest",
    "ResolveResponse",
    # Requirement schemas
    "RequirementCreate",
    "RequirementSourceResponse",
    "RequirementHistoryResponse",
    "RequirementResponse",
    "RequirementUpdate",
    "RequirementsListResponse",
    "RequirementReorderRequest",
    # PRD schemas
    "ExportFormat",
    "PaginatedResponse",
    "PRDExportJSON",
    "PRDExportSection",
    "PRDGenerateRequest",
    "PRDResponse",
    "PRDSection",
    "PRDStatusResponse",
    "PRDSummary",
    "PRDUpdateRequest",
    # User Story schemas
    "ReorderRequest",
    "STORIES_CSV_COLUMNS",
    "StoriesExportJSON",
    "StoriesGenerateRequest",
    "StoryBatchResponse",
    "StoryBatchStatusResponse",
    "StoryCreateRequest",
    "StoryExportFormat",
    "StoryExportItem",
    "StoryUpdateRequest",
    "UserStoryResponse",
]
