"""Pydantic schemas for API request/response validation."""

from app.schemas.jira_story import (
    JiraStoryCreate,
    JiraStoryResponse,
    JiraStoriesSaveRequest,
    JiraStoriesSaveResponse,
)
from app.schemas.auth import (
    TokenResponse,
    UserLogin,
    UserRegister,
    UserResponse,
)
from app.schemas.meeting import (
    ApplyResponse,
    ConflictResultResponse,
    MatchedRequirementResponse,
    MeetingItemCreate,
    MeetingItemReorderRequest,
    MeetingItemResponse,
    MeetingItemUpdate,
    MeetingListItemResponse,
    MeetingResponse,
    MeetingUpload,
    MergeSuggestionRequest,
    MergeSuggestionResponse,
    ResolveDecision,
    ResolveRequest,
    ResolveResponse,
    UploadResponse,
)
from app.schemas.project import (
    ExportStatusSchema,
    MemberSummary,
    MockupsStatusSchema,
    PRDStageStatusSchema,
    ProgressResponse,
    ProjectCreate,
    ProjectListResponse,
    ProjectResponse,
    ProjectStatsResponse,
    ProjectUpdate,
    RequirementsStatusSchema,
    SectionCount,
    StageStatusEnum,
    StageUpdateRequest,
    StoriesStatusSchema,
    calculate_progress,
)
from app.schemas.bug_report import (
    BugReportListResponse,
    BugReportResponse,
    BugStatusUpdate,
)
from app.schemas.feature_request import (
    CommentCreate,
    CommentResponse,
    CommentUpdate,
    FeatureRequestCreate,
    FeatureRequestListResponse,
    FeatureRequestResponse,
    FeatureRequestUpdate,
    FeatureStatusUpdate,
    UpvoteResponse,
)
from app.schemas.notification import (
    NotificationListResponse,
    NotificationResponse,
    UnreadCountResponse,
)
from app.schemas.project_member import (
    AddMemberRequest,
    ProjectMemberResponse,
    UpdateMemberRoleRequest,
    UserSearchResponse,
)
from app.schemas.requirement import (
    RequirementCreate,
    RequirementHistoryResponse,
    RequirementReorderRequest,
    RequirementResponse,
    RequirementsListResponse,
    RequirementSourceResponse,
    RequirementUpdate,
)
__all__ = [
    # Auth schemas
    "UserRegister",
    "UserLogin",
    "TokenResponse",
    "UserResponse",
    # Project schemas
    "ProjectCreate",
    "ProjectUpdate",
    "ProjectResponse",
    "ProjectListResponse",
    "MemberSummary",
    "SectionCount",
    "ProjectStatsResponse",
    "ProgressResponse",
    "StageStatusEnum",
    "StageUpdateRequest",
    "RequirementsStatusSchema",
    "PRDStageStatusSchema",
    "StoriesStatusSchema",
    "MockupsStatusSchema",
    "ExportStatusSchema",
    "calculate_progress",
    # Meeting schemas
    "MeetingUpload",
    "MeetingItemResponse",
    "MeetingResponse",
    "MeetingListItemResponse",
    "UploadResponse",
    "MeetingItemUpdate",
    "MeetingItemCreate",
    "MeetingItemReorderRequest",
    "MatchedRequirementResponse",
    "ConflictResultResponse",
    "ApplyResponse",
    "MergeSuggestionRequest",
    "MergeSuggestionResponse",
    "ResolveDecision",
    "ResolveRequest",
    "ResolveResponse",
    # Requirement schemas
    "RequirementCreate",
    "RequirementSourceResponse",
    "RequirementHistoryResponse",
    "RequirementResponse",
    "RequirementUpdate",
    "RequirementsListResponse",
    "RequirementReorderRequest",
    # JIRA Story schemas
    "JiraStoryCreate",
    "JiraStoryResponse",
    "JiraStoriesSaveRequest",
    "JiraStoriesSaveResponse",
    # Bug Report schemas
    "BugReportResponse",
    "BugReportListResponse",
    "BugStatusUpdate",
    # Feature Request schemas
    "FeatureRequestCreate",
    "FeatureRequestUpdate",
    "FeatureRequestResponse",
    "FeatureRequestListResponse",
    "FeatureStatusUpdate",
    "CommentCreate",
    "CommentUpdate",
    "CommentResponse",
    "UpvoteResponse",
    # Project member schemas
    "AddMemberRequest",
    "UpdateMemberRoleRequest",
    "ProjectMemberResponse",
    "UserSearchResponse",
    # Notification schemas
    "NotificationResponse",
    "NotificationListResponse",
    "UnreadCountResponse",
]
